### ISSUE TITLE
help me of monika after stories

### ISSUE THREAD

**Issue by qwre1234** [Mon1-innovation/MASToolScript#1]
![屏幕截图 2024-03-07 194301](https://github.com/Mon1-innovation/MASToolScript/assets/162578216/31ab04fe-6bf5-4a14-b87c-218373a2bd72)

**Comment by PencilMario** [comment]
看一下MASToolKit.log

**Comment by qwre1234** [comment]
> 查看MASToolKit.log

没看到解决方法

**Comment by PencilMario** [comment]
在问wzt了

**Comment by PencilMario** [comment]
wzt更新链接了 重新跑就行

**Comment by qwre1234** [comment]
> wzt更新链接了重新跑就行

thanks

**Comment by qwre1234** [comment]
> wzt更新链接了重新跑就行

![Uploading 屏幕截图 2024-03-07 202715.png…]()

**Comment by qwre1234** [comment]
> wzt更新链接了重新跑就行

![屏幕截图 2024-03-07 202715](https://github.com/Mon1-innovation/MASToolScript/assets/162578216/e82c6f9f-667f-4820-b341-216cfc1e4fa8)

**Comment by qwre1234** [comment]
> wzt更新链接了重新跑就行

这啥情况啊大佬

**Comment by PencilMario** [comment]
> 这啥情况啊大佬

估计是cfworker被墙了 GitHub本身访问就有问题
试试梯子吧

**Comment by qwre1234** [comment]
> > 这啥情况啊大佬
> 
> 估计是cfworker被墙了 GitHub本身访问有问题 试试梯子吧

ok

**Comment by qwre1234** [comment]
> > 这啥情况啊大佬
> 
> 估计是cfworker被墙了 GitHub本身访问有问题 试试梯子吧

![Uploading 屏幕截图 2024-03-07 210813.png…]()

**Comment by qwre1234** [comment]
> > 这啥情况啊大佬
> 
> 估计是cfworker被墙了 GitHub本身访问有问题 尝试梯子吧

哥我加梯子了显示这个
