### ISSUE TITLE
helpppppppppppp

### ISSUE THREAD

**Issue by LEVIAowo** [Mon1-innovation/MASToolScript#2]
[MASToolKit.log](https://github.com/user-attachments/files/15936170/MASToolKit.log)

how to resolve this thx
i dont know why is this happening TT

**Comment by PencilMario** [comment]
github api估计被墙了 等会再重试看看吧

**Comment by LEVIAowo** [comment]
好的！

> github api估计被墙了 等会再重试看看吧

这个等待时间只能看天意了是吗TT

**Comment by PencilMario** [comment]
是的



---Original---
From: ***@***.***&gt;
Date: Sat, Jun 22, 2024 18:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Mon1-innovation/MASToolScript] helpppppppppppp (Issue #2)




 
好的！
  
github api估计被墙了 等会再重试看看吧
  
这个等待时间只能看天意了是吗TT
