### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by MyWaifuMonika** [Mon1-innovation/MASToolScript#8]
[MASToolKit.log](https://github.com/user-attachments/files/18134069/MASToolKit.log)

**Comment by PencilMario** [comment]
https://lug.ustc.edu.cn/wiki/doc/smart-questions/
看起来运行正常，详细描述问题
其他issue我会关闭

**Comment by qinglin1674** [comment]
很抱歉，出现了一个未捕获的异常情况。

在加载脚本之前。
异常：找不到“chs.rpi”文件。

——完整回溯信息——————————————————————

完整回溯信息如下：
文件“C:\Users\Administrator\Desktop\已修改MAS_24.8.5_MiaoSIKI\renpy\bootstrap.py”，第295行，在“bootstrap”函数中
    renpy.main.main()
文件“C:\Users\Administrator\Desktop\已修改MAS_24.8.5_MiaoSIKI\renpy\main.py”，第300行，在“main”函数中
    renpy.loader.index_archives()
文件“C:\Users\Administrator\Desktop\已修改MAS_24.8.5_MiaoSIKI\renpy\loader.py”，第163行，在“index_archives”函数中
    fn = transfn(prefix + ".rpi")
文件“C:\Users\Administrator\Desktop\已修改MAS_24.8.5_MiaoSIKI\renpy\loader.py”，第615行，在“transfn”函数中
    raise Exception("Couldn't find file '%s'." % name)
异常：找不到“chs.rpi”文件。

Windows 8 - 6.2.9200
Ren'Py 6.99.12.4.2187 
i need help

**Comment by PencilMario** [comment]
首先，这不是安装器的问题

汉化版没有chs.rpi文件，看起来你在使用别人的整合包，你应该先询问整合包作者，或者尝试自行重装汉化补丁

**Comment by liuyun-666** [comment]
[MASToolKit.log](https://github.com/user-attachments/files/18230339/MASToolKit.log)

**Comment by PencilMario** [comment]
网络问题 或者你碰github速率墙了
